name: Bug Report
description: Create a bug report for Nothing Phone 2 kernel
labels: [Bug]

body:
  - type: markdown
    attributes:
      value: |
        ## Nothing Phone 2 Kernel Bug Report
        This kernel is specifically built for Nothing Phone 2 (Android 12, 5.10 kernel)

  - type: input
    attributes:
      label: Rom Used
      description: Your Rom used on Nothing Phone 2
      placeholder: 'e.g., Nothing OS, LineageOS, Pixel Experience'
    validations:
      required: true

  - type: input
    attributes:
      label: Android Version
      description: Your Android version (kernel is based on Android 12)
      placeholder: 'e.g., Android 12, 13, 14'
    validations:
      required: true

  - type: input
    attributes:
      label: WKSU Kernel Version
      description: Your WKSU kernel version number
      placeholder: 'e.g., 13971'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Manager
      description: Which KernelSU manager you're using
      options:
        - Wild KSU
        - KernelSU Next
        - KernelSU
        - MKSU
        - KowSU
        - RKSU
        - SukiSU
    validations:
      required: true

  - type: input
    attributes:
      label: Manager Version
      description: Your manager version
      placeholder: 'e.g., v0.0.165(13974)'
    validations:
      required: true

  - type: input
    attributes:
      label: Release Flashed
      description: Which release version you flashed
      placeholder: 'e.g., v1.5.12-r2'
    validations:
      required: true

  - type: input
    attributes:
      label: Full File Name
      description: The complete filename of the kernel you flashed
      placeholder: 'e.g., WKSU-13971-SUSFS_v1.5.12-android12-5.10.215-2024-12-Normal-12345678-make.zip'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: SUSFS Version
      description: Which SUSFS version variant you're using
      options:
        - v1.5.9
        - v1.5.12
    validations:
      required: true

  - type: input
    attributes:
      label: Last Working File Name
      description: The filename of the last working kernel (if any)
      placeholder: 'e.g., WKSU-13970-SUSFS_v1.5.9-android12-5.10.215-2024-12-Normal-12345678-make.zip'
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behaviour
      placeholder: |
        - 1. Go to '...'
        - 2. Click on '....'
        - 3. Scroll down to '....'
        - 4. See error

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    attributes:
      label: Logs
      description: If applicable, add crash or any other logs to help us figure out the problem.

  - type: textarea
    attributes:
      label: Extra info
      value: |
        - Device: Nothing Phone 2
        - ROM Used:
        - OS Version:
        - Kernel Version: Android 12 5.10
        - KernelSU (WKSU) Version:
        - SUSFS Version:
        - Manager App:
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
