name: Build Check - Nothing Phone Kernel

permissions:
  contents: write
  actions: write

on:
  push:
  workflow_dispatch:

jobs:
  build-check-nothing:
    name: Build Check Nothing Phone
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      os_patch_level: 'lts'
      revision: 'r1'
      sub_level: 'X'
